### PR TITLE
fix: failure when helmrepository and the helmrelease are in different namespaces

### LINKED ISSUE #16: Failure when the helmrepository and the helmrelease are in different namespaces
Hello,

We found an issue where we have the helmrelease in namespace X and the helmrepository in namespace Y `mta` fails to migrate the helmrelease with error:
```bash
FATA[0002] helmrepositories.source.toolkit.fluxcd.io "Y" not found
```
The command we run is:
```bash
mta helmrelease --name my-helmrelease --namespace X
```

### PR DESCRIPTION
**Pull request by nitishfy**
Fixes https://github.com/akuity/mta/issues/16

### CODE REVIEW

**Review by xavidop — APPROVED** [review]

File: cmd/helmrelease.go [hunk 1]
```diff
@@ -64,6 +65,10 @@ with kubectl.`,
 		helmReleaseNamespace, _ := cmd.Flags().GetString("namespace")
 		confirmMigrate, _ := cmd.Flags().GetBool("confirm-migrate")
 
+		if helmReleaseName == "" || helmReleaseNamespace == "" {
```
Comment (christianh814) [inline cmd/helmrelease.go:68]: This isn't needed. You can do this with cobra using [MarkFlagsRequiredTogether](https://pkg.go.dev/github.com/spf13/cobra@v1.7.0#Command.MarkFlagsRequiredTogether).

**Review by christianh814 — CHANGES_REQUESTED** [review]

File: cmd/helmrelease.go (hunk 1 above)
Comment (nitishfy) [reply cmd/helmrelease.go:68]: If we use the _MarkFlagsRequiredTogether_, we'll get an error for command that doesn't require either  of those flags such as `mta scan`.

Comment (christianh814) [reply cmd/helmrelease.go:68]: I believe you can get around that by just using `helmreleaseCmd.MarkFlagsRequiredTogether()` instead of `rootCmd` (requires testing)

Comment (christianh814) [reply cmd/helmrelease.go:68]: In the `init()` seciton of helmrelease.go I added

```
	rootCmd.MarkPersistentFlagRequired("name")
	rootCmd.MarkPersistentFlagRequired("namespace")
```

But in the root.go file I had to change it to a blank default

```
rootCmd.PersistentFlags().String("namespace", "", "Namespace of where the Kustomization or HelmRelease is")
```

Now I'm thinking of what was the problem before? The fact that we were defaulting to `flux-system`?

Comment (christianh814) [reply cmd/helmrelease.go:68]: Let's move forward with this and we can refactor it later cc @blakepettersson

**Review by christianh814 — APPROVED** [review]
