### PR TITLE
Fix: Produce valid manifest when helmrepository and the helmrelease are in different namespaces

### LINKED ISSUE #12: Failure when the helmrepository and the helmrelease are in different namespaces
Hello,

We found an issue where we have the helmrelease in namespace X and the helmrepository in namespace Y `mta` fails to migrate the helmrelease with error:
```bash
FATA[0002] helmrepositories.source.toolkit.fluxcd.io "Y" not found
```
The command we run is:
```bash
mta helmrelease --name my-helmrelease --namespace X
```

### PR DESCRIPTION
**Pull request by nitishfy**
Closes #12
## Before

```
> mta helmrelease --name diff-release --namespace non-existent
FATA[0000] helmrepositories.source.toolkit.fluxcd.io "podinfo" not found 
```

## After

```
 > mta helmrelease --name diff-release --namespace non-existent
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: -diff-release
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: podinfo
    helm:
      values: |
        replicaCount: 2
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.5.*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - Validate=false
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
```

### CODE REVIEW

File: cmd/helmrelease.go [hunk 1]
```diff
@@ -185,6 +187,15 @@ with kubectl.`,
 	},
 }
 
+func GetHelmRepoNamespace(helmRelease *helmv2.HelmRelease) string {
+	helmRepoNamespace := helmRelease.Spec.Chart.Spec.SourceRef.Namespace
+	if helmRepoNamespace == "" {
+		helmRepoNamespace = "default"
```
Comment (christianh814) [inline cmd/helmrelease.go]: I'm trying to think of a better default than `default`. Ideally we should default to the namespace of the helmRelease

```
if  helmRepoNamespace == "" {
        helmRepoNamespace = helmRelease.Namespace
}
```

Or maybe just `flux-system` (as that's the default for most flux users).

**Review by christianh814 — CHANGES_REQUESTED** [review]
Looks good, left one note

File: cmd/helmrelease.go (hunk 1 above)
Comment (nitishfy) [reply cmd/helmrelease.go]: The users will be coming from the Flux background, and according to the [Flux documentation](https://fluxcd.io/flux/components/source/helmrepositories/#helm-https-repository) the default value for the namespace is default. I think we should stick to default rather than any other namespace.

Comment (nitishfy) [reply cmd/helmrelease.go]: cc @hiddeco

**Review by christianh814 — APPROVED** [review]
lgtm!
